/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   saved-list-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {SavedListMixin};

declare namespace ArcComponents {


  /**
   * A mixin to be applied to a list that renders saved requests.
   * It contains methods to query for saved list and to search saved requests.
   */
  function SavedListMixin(base: Class|null): Class|null;
}
